services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-master
    ports:
      - "8080:8080"      # Web interface
      - "50000:50000"    # Agent communication
      - "2222:22"        # SSH access
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
    environment:
      - JENKINS_SLAVE_AGENT_PORT=50000
    restart: unless-stopped

  jenkins-agent-1:
    build:
      context: ./jenkins-agent
    container_name: jenkins-agent-1
    depends_on:
      - jenkins-master
    restart: unless-stopped

  jenkins-agent-2:
    build:
      context: ./jenkins-agent
    container_name: jenkins-agent-2
    depends_on:
      - jenkins-master
    restart: unless-stopped
